//
// Created by alejandro on 21/10/2023.
//

#ifndef ALGORITHMANDDATASTRUCTURE_BPLUSTREE_H
#define ALGORITHMANDDATASTRUCTURE_BPLUSTREE_H


class BPlusTree {

};


#endif //ALGORITHMANDDATASTRUCTURE_BPLUSTREE_H
