//
// Created by alejandro on 21/10/2023.
//

#ifndef ALGORITHMANDDATASTRUCTURE_CIRCULARLIST_H
#define ALGORITHMANDDATASTRUCTURE_CIRCULARLIST_H


class CircularList {

};


#endif //ALGORITHMANDDATASTRUCTURE_CIRCULARLIST_H
