//
// Created by alejandro on 21/10/2023.
//

#ifndef ALGORITHMANDDATASTRUCTURE_DOUBLELIST_H
#define ALGORITHMANDDATASTRUCTURE_DOUBLELIST_H


class DoubleList {

};


#endif //ALGORITHMANDDATASTRUCTURE_DOUBLELIST_H
