//
// Created by alejandro on 21/10/2023.
//

#ifndef ALGORITHMANDDATASTRUCTURE_FORWARDLIST_H
#define ALGORITHMANDDATASTRUCTURE_FORWARDLIST_H


class ForwardList {

};


#endif //ALGORITHMANDDATASTRUCTURE_FORWARDLIST_H
